name: "HybridCheck"
description: "Site for the HybridCheck R package for analysing recombination signals in DNA sequences"

paginate: 10

url: "ward9250.github.io/HybridCheck"

markdown: rdiscount
permalink: pretty
pygments: true
